export const queryKeys = {
  children: (userId) => ["children", userId],
  child: (userId, childId) => ["child", userId, childId],
  entitlement: (userId) => ["entitlement", userId],
  childSettings: (userId, childId) => ["child-settings", userId, childId],
  childApprovals: (userId, childId, filters = {}) => ["child-approvals", userId, childId, filters],
  childApproval: (userId, childId, approvalId) => ["child-approval", userId, childId, approvalId],
  childLibrary: (userId, childId, filters = {}) => ["child-library", userId, childId, filters],
  childProgress: (userId, childId, range = "30d") => ["child-progress", userId, childId, range],
  parentDashboard: (userId, range = "7d", simulate = "") => ["parent-dashboard", userId, range, simulate],
  exports: (userId, filters = {}) => ["parent-exports", userId, filters],
  exportJob: (userId, exportId) => ["parent-export", userId, exportId],
  familyReport: (userId) => ["family-report", userId],
  profile: (userId) => ["profile", userId],
  adminUsers: (userId, filters = {}) => ["admin-users", userId, filters],
  adminUser: (userId, targetId) => ["admin-user", userId, targetId],
  adminReports: (userId, filters = {}) => ["admin-reports", userId, filters],
  adminReport: (userId, reportId) => ["admin-report", userId, reportId],
  adminPermissions: (userId, filters = {}) => ["admin-permissions", userId, filters],
  adminRoleCatalog: (userId) => ["admin-role-catalog", userId],
  adminSystemLimits: (userId) => ["admin-system-limits", userId],
  adminRestrictions: (userId) => ["admin-restrictions", userId],
  adminMonitoring: (userId) => ["admin-monitoring", userId],
  adminStatistics: (userId, range = "7d") => ["admin-statistics", userId, range],
  adminAudit: (userId, filters = {}) => ["admin-audit", userId, filters],
  stories: (userId, filters = {}) => ["stories", userId, filters],
  contentCategories: (userId) => ["content-categories", userId],
  story: (userId, storyId) => ["story", userId, storyId],
  assets: (userId) => ["assets", userId],
  contentStatistics: (userId, range = "7d") => ["content-statistics", userId, range],
  storyPages: (userId, storyId) => ["story-pages", userId, storyId],
  storyRoles: (userId, storyId) => ["story-roles", userId, storyId],
  storyVocabulary: (userId, storyId) => ["story-vocabulary", userId, storyId],
  storyQuizzes: (userId, storyId) => ["story-quizzes", userId, storyId],
  storyPreview: (userId, storyId) => ["story-preview", userId, storyId],
};
